### ISSUE TITLE
Docker Renovate:latest on Gitlab-CI authentication error

### ISSUE THREAD

**Issue by raimund-schluessler** [renovatebot/config-help#162]
### Which Renovate are you using? CLI, App, or Pro
I use Docker renovate/renovate:latest

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab

### Configuration

`config.js:`
```js
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://<Gitlab_Instance_URL>/api/v4/',
	assignees: ['raimund.schluessler'],
	baseBranches: ['master'],
	labels: ['renovate'],
	logLevel: 'info',
	extends: ['config:base']
};
```

`.gitlab-ci.yml:`
```yml
image: docker:latest

services:
  - docker:dind

renovate:
  stage: build
  script:
    - docker run -e GITLAB_TOKEN="$GITLAB_TOKEN" -e GITHUB_TOKEN="$GITHUB_TOKEN" -v $PWD/config.js:/usr/src/app/config.js renovate/renovate:latest $(cat repositories.txt | xargs)
```

I followed this guide https://medium.com/@mikebarkmin/renovate-your-gitlab-projects-automatically-bbba188669b5 by @mikebarkmin, the only thing I changed is `renovate/renovate:13` to `renovate/renovate:latest`.

### Have you checked the logs? Don't forget to include them if relevant

I see the following error in the logs:
```
Status: Downloaded newer image for renovate/renovate:latest
FATAL: Fatal error: No authentication found for platform https://<Gitlab_Instance_URL>/api/v4/ (gitlab)
       "err": {
         "message": "No authentication found for platform https://<Gitlab_Instance_URL>/api/v4/ (gitlab)",
         "stack": "Error: No authentication found for platform https://<Gitlab_Instance_URL>/api/v4/ (gitlab)\n    at Object.parseConfigs (/usr/src/app/lib/config/index.js:98:11)"
```

### What is your question?

Why does this configuration work with renovate:13, but not with renovate:latest? I remember to have read that the credential handling changed, but couldn't find the correct/current way to configure the authentication now.

**How do I configure authentication for Gitlab for renovate:latest correctly?**

**Comment by rarkins** [comment]
Please rename GITLAB_TOKEN to RENOVATE_TOKEN and GITHUB_TOKEN to GITLAB_COM_TOKEN. These changed in Renovate v14

Make sure also that platform is configured as GitLab, in config or RENOVATE_PLATFORM=gitlab

**Comment by raimund-schluessler** [comment]
> Please rename GITLAB_TOKEN to RENOVATE_TOKEN and GITHUB_TOKEN to GITLAB_COM_TOKEN. These changed in Renovate v14

Thanks for the fast help. I assume, you meant to rename `GITHUB_TOKEN` to `GITHUB_COM_TOKEN`. In fact this is what I did and what works fine.

For the record the working config:

`config.js:`
```js
module.exports = {
	platform: 'gitlab',
	endpoint: 'https://<Gitlab_Instance_URL>/api/v4/',
	assignees: ['raimund.schluessler'],
	baseBranches: ['master'],
	labels: ['renovate'],
	logLevel: 'info',
	extends: ['config:base']
};
```

`.gitlab-ci.yml:`
```yml
image: docker:latest

services:
  - docker:dind

renovate:
  stage: build
  script:
    - docker run -e RENOVATE_TOKEN="$RENOVATE_TOKEN" -e GITHUB_COM_TOKEN="$GITHUB_COM_TOKEN" -v $PWD/config.js:/usr/src/app/config.js renovate/renovate:latest $(cat repositories.txt | xargs)
```
