### ISSUE TITLE
[Question] Is there documentation for setting up maven private repositories?

### ISSUE THREAD

**Issue by kszilagyiOT** [renovatebot/config-help#187]
### Which Renovate are you using? CLI, App, or Pro
CLI (docker)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant
N/A

### What is your question?
 Is there documentation for setting up maven private repositories? I am trying to find it out from this MR what I meant to do: https://github.com/renovatebot/renovate/pull/3327
I concluded that I should do something like this, is this correct? (I can't try it out right now unfortunately).
```yaml
     hostRules: [
        {
          host: '<host-name>'
          platform: 'maven',
          username: '<your-username>',
          password: '<your-password>',
        },
      ],
```
 Documenting this would be really useful.

Thanks,
Kristof
