### ISSUE TITLE
ERROR: GitHub App ID/Key is not accepted (Pro & GitHub Ent)

### ISSUE THREAD

**Issue by tknickman** [renovatebot/config-help#266]
### Which Renovate are you using? CLI, App, or Pro
>Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
> GitHub (Internally Hosted Enterprise v2.16.7) 

### Have you checked the logs? Don't forget to include them if relevant
```
docker-compose up -d
renovate_db_1 is up-to-date
Recreating renovate_server_1 ... done
docker-compose logs -f server
Attaching to renovate_server_1
server_1  |  INFO: Renovate Pro starting
server_1  |  INFO: Initializing github platform
server_1  |  INFO: Renovate Pro is running in Evaluation mode
server_1  |  INFO: Using GitHub endpoint: https://api.{hosted-gh-url}/
server_1  |  INFO: GITHUB_APP_KEY not set - attempting to read pem file from disk
server_1  |  INFO: Read private key from disk
server_1  | ERROR: GitHub App ID/Key is not accepted
server_1  |        "err": {
server_1  |          "name": "RequestError",
server_1  |          "code": "EAI_AGAIN",
server_1  |          "host": "api.{hosted-gh-url}",
server_1  |          "hostname": "api.{hosted-gh-url}",
server_1  |          "method": "GET",
server_1  |          "path": "/app",
server_1  |          "protocol": "https:",
server_1  |          "url": "https://api.{hosted-gh-url}/app",
server_1  |          "gotOptions": {
server_1  |            "path": "/app",
server_1  |            "protocol": "https:",
server_1  |            "slashes": true,
server_1  |            "auth": null,
server_1  |            "host": "api.{hosted-gh-url}",
server_1  |            "port": null,
server_1  |            "hostname": "api.{hosted-gh-url}",
server_1  |            "hash": null,
server_1  |            "search": null,
server_1  |            "query": null,
server_1  |            "pathname": "/app",
server_1  |            "href": "https://api.{hosted-gh-url}/app",
server_1  |            "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
server_1  |            "headers": {
server_1  |              "user-agent": "got/9.5.1 (https://github.com/sindresorhus/got)",
server_1  |              "accept": "application/vnd.github.machine-man-preview+json",
server_1  |              "authorization": "** redacted **",
server_1  |              "accept-encoding": "gzip, deflate"
server_1  |            },
server_1  |            "hooks": {
server_1  |              "beforeRequest": [],
server_1  |              "beforeRedirect": [],
server_1  |              "beforeRetry": [],
server_1  |              "afterResponse": []
server_1  |            },
server_1  |            "decompress": true,
server_1  |            "throwHttpErrors": true,
server_1  |            "followRedirect": true,
server_1  |            "stream": false,
server_1  |            "form": false,
server_1  |            "json": true,
server_1  |            "cache": false,
server_1  |            "useElectronNet": false,
server_1  |            "method": "GET",
server_1  |            "forceRefresh": true
server_1  |          },
server_1  |          "message": "getaddrinfo EAI_AGAIN api.{hosted-gh-url} api.{hosted-gh-url}:443",
server_1  |          "stack": "RequestError: getaddrinfo EAI_AGAIN api.{hosted-gh-url} api.{hosted-gh-url}:443\n    at ClientRequest.request.once.error (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:165:14)\n    at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:187:15)\n    at ClientRequest.origin.emit.args (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:392:9)\n    at TLSSocket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"
server_1  |        },
server_1  |        "body": undefined
renovate_server_1 exited with code 0
```

## Relevant Files

1. `docker-compose`
```
version: '3.6' # earlier docker-compose versions are also fine
services:
  # Renovate Pro uses a PostgreSQL database to manage job queuing
  # This database is used only by Renovate and not necessary/desirable to expose to the outside world
  db:
    image: postgres:10.8-alpine
    restart: on-failure
    # Persisting PostgreSQL's data is desirable
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # Renovate Pro runs as a single long-lived server
  server:
    image: renovate/pro:0.15.3
    restart: on-failure
    depends_on:
      - db
    # The below environment variables can be passed through from the server's env, or hardcoded into the docker-compose.yml file
    environment:
      - ACCEPT_AGREEMENT=y
      - LICENSE_MODE=
      - LICENSE_NAME=
      - RENOVATE_ENDPOINT=https://api.{hosted-gh-url}/
      - GITHUB_APP_ID=2
      - RENOVATE_PLATFORM=github
      - GITHUB_COM_TOKEN={redacted}
    ports:
      - "80:8080" # Receive webhooks on port 80
    volumes:
      # You can optionally mount the GitHub private key instead of exposing it in env
      - "./renovate.private-key.pem:/usr/src/app/renovate.private-key.pem"
      - "./.npmrc:/home/ubuntu/.npmrc"
      - "./config.js:/usr/src/app/config.js"
```

2. `config.js`
```
module.exports = {
        logLevel: 'debug',
        extends: ['config:base']
};
```

### What is your question?

Does this look like the correct set of config options? I followed doc set [here](https://github.com/renovatebot/pro/blob/master/docs/configuration-github.md)

To troubleshoot.
1. Verified the key / App ID. 
2. Tried switching from the mounted key as a volume to specifying the key as `GITHUB_APP_KEY` by adding the newlines as described in the docs ([here](https://github.com/renovatebot/pro/blob/master/docs/configuration-github.md#configure-renovate-pro)) but it results in the same error.
3. Tried swapping around the `RENOVATE_ENDPOINT` to a few other options like `https://{hosted-gh-url}/api/v3/`

Also, if we're using defaults, do we need to specify the `Webhook URL` from the github app config in the renovate config anywhere? 

Thanks!!
