### ISSUE TITLE
[Question] webhook URI not found

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#315]
### Which Renovate are you using? CLI, App, or Pro
pro self hosted kubernetes

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
github

### Have you checked the logs? Don't forget to include them if relevant
`{"url":"/webhook","message":"Not found"}`

### What is your question?
I followed the instructions when configuring renovate

Container port:
```
containers:
        - name: renovate-pro
          image: renovate/pro:0.16.0-pre.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
```
Kube Node Port:
```
---
apiVersion: v1
kind: Service
metadata:
  name: renovate-pro-service
  labels:
    run: renovate-pro-service
spec:
  ports:
  - nodePort: 30600
    port: 8080
    protocol: TCP
    targetPort: 8080
```

Example: 
```
[quentinmoss@localtoast-v2.local]$ curl -I https://renovate.honeyy.com/
HTTP/2 200
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 15
etag: W/"f-v/Y1JusChTxrQUzPtNAKycooOTA"
date: Thu, 01 Aug 2019 17:58:52 GMT
via: 1.1 google
alt-svc: clear
```

```
[quentinmoss@localtoast-v2.local]$ curl -I https://renovate.honeyy.com/webhook
HTTP/2 404
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 40
etag: W/"28-jssxFe2vaYFeVyMORJJB+Lr/WT4"
date: Thu, 01 Aug 2019 17:59:21 GMT
via: 1.1 google
alt-svc: clear
```
