### ISSUE TITLE
Gradle support (build.gradle)

### ISSUE THREAD

**Issue by Blade00Master** [renovatebot/config-help#636]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I've integrated renovate in our gradle project. Renovate works as expected for the Dockerfile and opened a merge request to update the image version. But not for the build.gradle file. Do i need to activate gradle support or change the syntax? 
In the build.gradle file the dependencies are defined as follow:

    implementation('com.fasterxml.jackson.core:jackson-databind:2.10.2')

It seems that renovate don't search through the file.

Thank you for the help!

**Comment by viceice** [comment]
Can you please post your configuration and debug log.

**Comment by Blade00Master** [comment]
I see in the logs that the renovate plugin is missing. I think that is because i use a abstraction for the gitlab ci and not the renovate directly. (https://github.com/Morton/renovate-gitlab-ci) 

But here the logs:
`...
> renovate-gitlab-ci@0.0.0 start /renovate
 > renovate --platform=gitlab --endpoint=$CI_API_V4_URL $CI_PROJECT_PATH
 (node:31) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
  INFO: Repository started (repository=<>)
        "renovateVersion": "19.181.0"
  WARN: Gradle extraction failed (repository=<>)
        "errMessage": "Command failed: ./gradlew --init-script renovate-plugin.gradle renovate\n"
  INFO: Extraction statistics (repository=<>)
        "stats": {
          "managers": {
            "gitlabci": {"fileCount": 1, "depCount": 1},
            "gradle-wrapper": {"fileCount": 1, "depCount": 1}
          },
          "fileCount": 2,
          "depCount": 2
        }
  INFO: Repository finished (repository=<>)
 Job succeeded`

**Comment by viceice** [comment]
You should use our renovat [slim](https://hub.docker.com/r/renovate/renovate/tags/?page=1&name=slim) docker image as base.

**.gitlab-ci.yml**
```yaml
renovate:
  image:
    name: renovate/renovate:slim
  script:
    - renovate --version
```

**Comment by viceice** [comment]
if you need to run tools like gradle you  need to map the host docker socket and `/tmp` for the slim image to work

Alternate is to set `RENOVATE_BINARY_SOURCE=` to empty and use our included `install-tool` to install java

Needs to be run as root (default renovate user is ubuntu - 1000)
```sh
install-tool java 8
```

**Comment by viceice** [comment]
OK, found a small bug fixed in renovatebot/docker-renovate#21, should be live in a few minutes for v19.231.8 only

**Comment by viceice** [comment]
my gitlab pipeline:

```yml
variables:
  RENOVATE_ARGS: "--log-file=renovate.log --log-file-level=debug"

# templates
.base:
  image:
    name: renovate/renovate:19.231.8-slim@sha256:bf041f6cdacf96021df1f50e97449883d8e223db06184b2a3025a568c6f6c259
  artifacts:
    paths:
      - renovate.log

.deploy:
  extends: .base
  stage: deploy
  tags:
    - renovate
  script:
    - renovate $RENOVATE_ARGS

# jobs
test:
  extends: .base
  stage: test
  script:
    - renovate --version $RENOVATE_ARGS

deploy-dry-run:
  extends: .deploy
  except:
    - master
  script:
    - renovate --dry-run $RENOVATE_ARGS

deploy:
  extends: .deploy
  only:
    - master
```

renovate updates itself while doing a dry-run for test updates

**Comment by kaisermario** [comment]
> if you need to run tools like gradle you need to map the host docker socket and `/tmp` for the slim image to work
> 
> Alternate is to set `RENOVATE_BINARY_SOURCE=` to empty and use our included `install-tool` to install java
> 
> Needs to be run as root (default renovate user is ubuntu - 1000)
> 
> ```shell
> install-tool java 8
> ```

Do you have an hint for me how to map host docker socket in gitlab ci runner configuration?

**Comment by viceice** [comment]
```toml
[[runners]]
  name = "renovater"
  url = "https://gitlab.domain.com/"
  token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  executor = "docker"
  limit = 1
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/tmp:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""
```
