### ISSUE TITLE
Renovate github action not discovering repo

### ISSUE THREAD

**Issue by arnabkd** [renovatebot/config-help#760]
### Which Renovate are you using?

Self-hosted Renovate (in Github Actions)

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant
This part is relevant:
`.... WARN: No repositories found - did you want to run with flag --autodiscover?`

### What would you like to do?
Simply to run renovate using the github action.
Here is the repository with the relevant code:
https://github.com/arnabkd/nkk-scraper

The renovate.yml file in github workflows:
```
name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v1.0.0 
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.renovatekey }}
```

And here is the renovate-config.js file:
```
module.exports =   
{
  // Set to false even though this is default to guard against future defaults
  "automerge": false,

  // set-build-properties fails if "renovate/" is used
  "branchPrefix": "renovate-",
  "extends": [
    "config:base"
  ],
  // Ensure that major is never automerged
  "major": {
    "automerge": false
  },
  "masterIssue": true,
  // Default 0, but use this to prevent renovate from spamming PRs
  "prConcurrentLimit": 5,
  // Wait for builds to complete (successful or otherwise) before creating PRs
  "prCreation": "not-pending",
  "stabilityDays": 10,
  "timezone": "Europe/Oslo"
}
```

I first tried using the renovate.json but the github action complained about a syntax error (no ":" allowed). So I switched to renovate-config.js. That went fine (as in the action succeeded) but it never discovered the repository.
