### ISSUE TITLE
Same dependency different version for circleCI

### ISSUE THREAD

**Issue by Chumper** [renovatebot/config-help#851]
### Which Renovate are you using?
Self Hosted `23.20.0`

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

Assuming that we have a CircleCI config like this:
```
version: 2.1
executors:
  python-3-6:
    docker:
      - image: circleci/python:3.6.12
  python-3-7:
    docker:
      - image: circleci/python:3.7.9
  python-3-8:
    docker:
      - image: circleci/python:3.8.5
```

We are using this to make sure that our library is tested in python `3.6`, `3.7` and `3.8`.

Now when Renovate runs it wants to update the dependencies like this

| Package | Type | Update | Change |
|---|---|---|---|
| circleci/python | docker | minor | `3.7.9` -> `3.8.5` |
| circleci/python | docker | minor | `3.6.12` -> `3.8.5` |

which makes sense, but in this case we do not want to update the version `3.6` and `3.7`.

As far as I know we cannot use `ignoreDeps` because the name for all three is the same.
So how can we distinguish between these three occurences?

Is there a way for that? We would like to have updates for for all version, however limited to the minor version.
