### ISSUE TITLE
Format currentValue in a regexManager

### ISSUE THREAD

**Issue by ctison** [renovatebot/config-help#860]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

Hello, I would like to know if it is possible to format a `currentValue` in a `regexManager`.

For example, I have in a `.github/workflows/cicd.yaml`:
```yaml
name: CI/CD
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31 # golangci/golangci-lint
```

My `renovate.json` looks like this:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "regexManagers": [{
    "fileMatch": [
      "^.github/workflows/cicd.yaml$"
    ],
    "matchStrings": [
      "\n +version: (?<currentValue>.+) # (?<depName>.+)\n"
    ],
    "datasourceTemplate": "github-releases"
  }]
}
```

[Golang CI Lint Action](https://github.com/golangci/golangci-lint-action) requires the version of [Golang CI Lint](https://github.com/golangci/golangci-lint) to be specified down to the minor version: i.e. v1.31.0 -> v1.31.

Is this possible ?

Many thanks
