### ISSUE TITLE
Authentication failure even if token is correct

### ISSUE THREAD

**Issue by FadedCoder** [renovatebot/config-help#893]
### Which Renovate are you using?

Renovate Open Source CLI (Docker)

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
FATAL: Authentication failure
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "KKRk7eYqQ",
           "msg": "Authentication failure"
         }
       ]
```

### What would you like to do?

I've verified that the token is correct with `curl --header "Authorization: Bearer <TOKEN>" "https://git.my.site/api/v4/projects"`

Everything was working fine till a few days ago when it broke w/o any user interaction. I'm guessing there was an update in the image?

Here's my docker-compose.yml:
```
version: "3"
services:
  app:
    container_name: 'renovate-bot'
    image: "renovate/renovate:latest"
    environment:
      RENOVATE_TOKEN: <GITLAB TOKEN WITH API SCOPE>
      GITHUB_COM_TOKEN: <GITHUB READ ONLY TOKEN>
    restart: always
    volumes:
      - './config.js:/usr/src/app/config.js'
```
and my config.js:
```
module.exports = {
  endpoint: 'https://git.my.site/api/v4/',
  platform: 'gitlab',
  logLevel: 'debug',
  onboardingConfig: {
    extends: ['config:base'],
  },
  autodiscover: true,
  repositories: []
};
```
