### ISSUE TITLE
Deprecated! Please use global 'renovate' command. && Config needs migrating

### ISSUE THREAD

**Issue by Albertbol** [renovatebot/config-help#901]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

Gitlab pipeline log:
$ ln -sF $CI_PROJECT_DIR/config.js /usr/src/app/
$ node /usr/src/app/dist/renovate.js
 WARN: Deprecated! Please use global 'renovate' command.
 WARN: Config needs migrating

### What would you like to do?
I would like to ask about 2 WARN messages in GitLab pipeline:
` WARN: Deprecated! Please use global 'renovate' command.`
And
` WARN: Config needs migrating`

I could not find info about solving those 2 issues.

Here is my `.gitlab-ci.yml`

```
renovate:
  variables:
    RENOVATE_TOKEN: $GITLAB_ACCESS_TOKEN
    GITHUB_COM_TOKEN: $GITHUB_ACCESS_TOKEN
    DOCKER_USERNAME: $CI_REGISTRY_USER # needed to allow Renovate to check against GitLabs own Docker container registry
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
  image: registry.gitlab.com/***/container-registry:renovate
  script:
    - ln -sF $CI_PROJECT_DIR/config.js /usr/src/app/
    - node /usr/src/app/dist/renovate.js
  only:
    - schedules
```

`config.js`:
```
module.exports = {
    platform: 'gitlab',
    baseBranches: ['master'],
    labels: ['renovate'],
    rebaseWhen: 'auto',
    semanticCommits: true,
    major: {
      automerge: false
    },
    repositories: [
      '*****'
    ],
    extends: [
      'config:base',
      ":pinAllExceptPeerDependencies"
    ]
  };
```
`renovate.json`:
```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
  }
```
