### ISSUE TITLE
Not finding Renovate folder

### ISSUE THREAD

**Issue by billyto** [renovatebot/config-help#914]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
➜  local kubectl logs renovate-vnccd
[dumb-init] renovate: No such file or directory
```

### What would you like to do?

I'm deploying renovate via Kubernetes, initially in my local env (minikube). 
* The configuration sets up a dry run
* Specifying the config file (the pod is getting the file deployed)
*  And setting up the renovate working dir (I can confirm that the dir exists). 

but when I run the Kubernetes CronJob, it fails due to not able to find a **"renovate"** file or dir.

I'm wondering what is this renovate file/dir, and where can be configured; any hint is greatly appreciated.

Thanks!

Here is the yaml:

```
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: renovate-config
  data:
    config.json: |-
      {
        "logLevel" : "debug",
        "dryRun" : "true"
      }
      
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: renovate/renovate:23.22.1
            name: renovate-bot
            # command: [ "/bin/sh", "-c", "ls -l /tmp/renovate/" ]  
            env:
              - name: RENOVATE_PLATFORM
                value: 'github'
              - name: GITHUB_COM_TOKEN
                value: 'xxxxx'
              - name: RENOVATE_TOKEN
                value: 'xxxxx'
              - name: RENOVATE_AUTODISCOVER
                value: 'true'
              - name: RENOVATE_BASE_DIR
                value: '/tmp/renovate/'
            volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/
            - name: work-volume
              mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
```

**Comment by rarkins** [comment]
This should be where the `renovate` binary is located: https://github.com/renovatebot/docker-renovate/blob/3b5bb2aa26abadaf2c44488b1ca4f4ce1f96d0b1/Dockerfile#L74

**Comment by viceice** [comment]
@billyto I think it can be caused by the volume mount. can you check `/usr/src/app/` dir withcommand like `command: [ "/bin/sh", "-c", "ls -l /usr/src/app/" ]`

**Comment by billyto** [comment]
@viceice seems like the dir is present and has the config file, see command result

```
total 0
lrwxrwxrwx 1 root root 18 Oct  9 12:47 config.json -> ..data/config.json
```

**Comment by viceice** [comment]
@billyto Your problem is, that kubernets is hiding our required renovate files in `/usr/src/app/`. So your solution is to mount the volume to another folder and set `RENOVATE_CONFIG_FILE` env

```yml
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: renovate-config
  data:
    config.json: |-
      {
        "logLevel" : "debug",
        "dryRun" : "true"
      }
      
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: renovate/renovate:23.22.1
            name: renovate-bot
            # command: [ "/bin/sh", "-c", "ls -l /tmp/renovate/" ]  
            env:
              - name: RENOVATE_PLATFORM
                value: 'github'
              - name: GITHUB_COM_TOKEN
                value: 'xxxxx'
              - name: RENOVATE_TOKEN
                value: 'xxxxx'
              - name: RENOVATE_AUTODISCOVER
                value: 'true'
              - name: RENOVATE_BASE_DIR
                value: '/tmp/renovate/'
              - name: RENOVATE_CONFIG_FILE
                value: /opt/renovate/config.json
            volumeMounts:
            - name: config-volume
              mountPath: /opt/renovate/
            - name: work-volume
              mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
```
