### ISSUE TITLE
How to setup caching between executions

### ISSUE THREAD

**Issue by candrews** [renovatebot/config-help#932]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted
### What would you like to do?

I'd like my GitLab job to appropriately cache data between runs so each job runs faster: https://docs.gitlab.com/ee/ci/yaml/README.html#cache

Here's my `.gitlab-ci.yml`:
```yaml
renovate-run:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  image: renovate/renovate
  script:
    - renovate
```

I think I need to enable `persistRepoData` in config.js. And I believe I need to set the `TMPDIR` or `RENOVATE_TMPDIR` variables to point to `$(pwd)/something` so Gitlab CI can cache them. But should I cache the whole `RENOVATE_TMPDIR` or just a subdirectory within it? Or is there a more appropriate way to do this?
