### ISSUE TITLE
GitLab Private Maven Registry and CI_JOB_TOKEN

### ISSUE THREAD

**Issue by mrclrchtr** [renovatebot/config-help#998]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

`DEBUG: Content is not found for Maven url: https://gitlab.com/api/v4/groups/XXXXXXX/-/packages/maven/XXXXX/maven-metadata.xml (repository=xxx/xxx/xxx)`

### What would you like to do?

I want to use a private GitLab Maven Registry. The project is configured as shown here: https://docs.gitlab.com/ee/user/packages/maven_repository/#authenticate-with-a-ci-job-token-in-maven
We use the settings.xml and inject the CI_JOB_TOKEN.

```
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/SETTINGS/1.1.0"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
    <servers>
        <server>
            <id>gitlab-maven</id>
            <configuration>
                <httpHeaders>
                    <property>
                        <name>Job-Token</name>
                        <value>${env.CI_JOB_TOKEN}</value>
                    </property>
                </httpHeaders>
            </configuration>
        </server>
    </servers>
</settings>
```

And in the pom.xml:

```
 <repositories>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/groups/XXXXX/-/packages/maven</url>
        </repository>
    </repositories>
```

How can I provide this CI_JOB_TOKEN to the Renovate bot in the GitLab pipeline?

We have tried this gitlab-ci config:
```
Renovate:
  image: renovate/renovate:23.86.1
  stage: renovate
  variables:
    RENOVATE_CONFIG_FILE: 'config.js'
    RENOVATE_HOST_RULES: '{"hostName":"gitlab.com","token":"${CI_JOB_TOKEN}"}'
  script:
    - renovate
```

Is this the right approach? In the log I could not see that the hostRule is used.
